project:
  type: website
  output-dir: docs

website:
  title: "econ_3201_assignment_1_Chen_demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

