project:
  type: website
  output-dir: docs

website:
  title: "econ_3201_assignment_1_Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

